version: '3'

services:
  inktober_bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - inktober_postgres
    volumes:
      - ./:/app

  inktober_postgres:
    image: postgres:10-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
