day_themes = {
    1: "Spooky/Hollow",
    2: "Spooky/Hollow",
    3: "Spooky/Hollow",
    4: "Runic/Creature",
    5: "Runic/Creature",
    6: "Runic/Creature",
    7: "Pumpkin/Party",
    8: "Pumpkin/Party",
    9: "Pumpkin/Party",
    10: "Realistic/Blob",
    11: "Realistic/Blob",
    12: "Realistic/Blob",
    13: "Magic/Machine",
    14: "Magic/Machine",
    15: "Magic/Machine",
    16: "Witch/Market",
    17: "Witch/Market",
    18: "Witch/Market",
    19: "Giant/Black Cat",
    20: "Giant/Black Cat",
    21: "Giant/Black Cat",
    22: "Flight/Illusion",
    23: "Flight/Illusion",
    24: "Flight/Illusion",
    25: "Bunny/Thief",
    26: "Bunny/Thief",
    27: "Bunny/Thief",
    28: "Unknown/Afterlife",
    29: "Unknown/Afterlife",
    30: "Unknown/Afterlife",
    31: "All your prompts in a single picture/montage",
}
